[package]
name = "remote-friend-client"
version = "0.1.0"
edition = "2021"

[dependencies]
remote-friend-common = { path = "../common" }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
image = { version = "0.25" }
openh264 = "0.9"
eframe = "0.32"
egui = "0.32"
rfd = "0.15"
